# Generated by Django 4.0.3 on 2022-03-11 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('planet', models.CharField(default='Mars', max_length=128)),
                ('name', models.CharField(default='base_1', max_length=128)),
            ],
        ),
    ]
