# Generated by Django 4.0.3 on 2022-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
